// ============================================================
// NameMatch – Canonical Name Type System
//
// NormalizedNameRecord is the single source-of-truth type
// that bridges the UI layer (BabyName) and the algorithm
// layer (NameRecord from supabase.ts).
//
// All providers normalize to this type.
// All algorithms operate on this type.
// UI components read this type (it's a superset of BabyName).
// ============================================================

import type { BabyName, Region } from '../types';

// ─────────────────────────────────────────────────────────────
// Enums / Union types
// ─────────────────────────────────────────────────────────────

export type GenderUsage = 'predominantly_male' | 'predominantly_female' | 'unisex';

export type TrendDirection = 'rising' | 'stable' | 'falling' | 'classic' | 'unknown';

export type NameSource =
  | 'local_seed'    // src/data/names.ts static array
  | 'supabase'      // Supabase `names` table (enriched / user-curated)
  | 'ssa_us'        // TODO: US Social Security Administration open data
  | 'ons_uk'        // TODO: UK Office for National Statistics
  | 'insee_fr'      // TODO: French INSEE baby name data
  | 'behindthename' // TODO: BehindTheName public API
  | 'ai_suggested'; // Generated by AI, not verified

// ─────────────────────────────────────────────────────────────
// Core canonical type
// ─────────────────────────────────────────────────────────────

export interface NormalizedNameRecord {
  // ── Identity ──────────────────────────────────────────────
  id: string;
  displayName: string;               // "Zoë" — rendered as-is
  normalizedName: string;            // "zoe" — ASCII, lowercase, diacritics stripped

  // ── Demographics ──────────────────────────────────────────
  language: string | null;           // primary language family ("Romance", "Germanic"…)
  country: string | null;            // primary associated country (ISO-style: "France")
  genderUsage: GenderUsage;          // usage category
  gender: 'boy' | 'girl' | 'neutral'; // retained for UI compat

  // ── Content ───────────────────────────────────────────────
  meaning: string | null;
  origin: string | null;             // free-text origin, e.g. "Italian / Latin"
  pronunciation: string | null;      // phonetic guide, e.g. "LOO-kah"
  variants: string[];                // alternate spellings ["Lucia","Lucía","Lucie"]

  // ── Popularity & Trend ────────────────────────────────────
  popularityRank: number | null;     // 1 = most popular (country or worldwide)
  popularityScore: number | null;    // 0–1000 normalized score (higher = more popular)
  trendDirection: TrendDirection;

  // ── Phonetic / Similarity ─────────────────────────────────
  phoneticKey: string | null;        // Soundex key for phonetic grouping

  // ── Tagging ───────────────────────────────────────────────
  tags: string[];                    // merged from style_tags + computed DNA tags

  // ── Region / Locale ───────────────────────────────────────
  region: string;                    // app region key ('EU','US','WORLDWIDE'…)
  is_worldwide: boolean;

  // ── Provenance ────────────────────────────────────────────
  source: NameSource;
  lastUpdated: string;               // ISO timestamp

  // ── Backward-compat aliases (UI layer uses these) ─────────
  name: string;                      // alias → displayName (always in sync)
  style_tags: string[];              // alias → tags
  popularity_score: number | null;   // alias → popularityScore
}

// ─────────────────────────────────────────────────────────────
// Legacy types — kept for import compat; prefer NormalizedNameRecord
// ─────────────────────────────────────────────────────────────

/** @deprecated Use NormalizedNameRecord */
export type LegacyBabyName = {
  id: string;
  name: string;
  meaning: string;
  origin: string;
  gender: 'boy' | 'girl' | 'neutral';
  country?: string;
  region: string;
  is_worldwide: boolean;
  created_at?: string;
  popularity_rank?: number;
  trend?: 'rising' | 'stable' | 'classic';
  pronunciation?: string;
  similar_names?: string[];
};

/** @deprecated Use NormalizedNameRecord */
export type LegacyNameRecord = {
  id: string;
  name: string;
  gender: string | null;
  origin: string | null;
  meaning: string | null;
  style_tags: string[] | null;
  popularity_score: number | null;
};

// ─────────────────────────────────────────────────────────────
// Adapters
// ─────────────────────────────────────────────────────────────

const NOW = new Date().toISOString();

/** Convert a legacy BabyName (static seed) into NormalizedNameRecord */
export function adaptBabyName(b: LegacyBabyName): NormalizedNameRecord {
  const norm = normalizeStr(b.name);
  return {
    id: b.id,
    displayName: b.name,
    normalizedName: norm,
    name: b.name,
    language: originToLanguageFamily(b.origin),
    country: b.country ?? null,
    genderUsage: genderToUsage(b.gender),
    gender: b.gender,
    meaning: b.meaning ?? null,
    origin: b.origin ?? null,
    pronunciation: b.pronunciation ?? null,
    variants: [],
    popularityRank: b.popularity_rank ?? null,
    popularityScore: popularityRankToScore(b.popularity_rank),
    trendDirection: trendStringToDirection(b.trend),
    phoneticKey: soundex(norm),
    tags: [],
    style_tags: [],
    region: b.region,
    is_worldwide: b.is_worldwide,
    source: 'local_seed',
    lastUpdated: b.created_at ?? NOW,
    popularity_score: popularityRankToScore(b.popularity_rank),
  };
}

/** Convert a legacy Supabase NameRecord into NormalizedNameRecord */
export function adaptNameRecord(n: LegacyNameRecord, region = 'WORLDWIDE'): NormalizedNameRecord {
  const norm = normalizeStr(n.name);
  const g = (n.gender === 'boy' || n.gender === 'girl') ? n.gender : 'neutral';
  return {
    id: n.id,
    displayName: n.name,
    normalizedName: norm,
    name: n.name,
    language: originToLanguageFamily(n.origin),
    country: null,
    genderUsage: genderToUsage(g),
    gender: g,
    meaning: n.meaning ?? null,
    origin: n.origin ?? null,
    pronunciation: null,
    variants: [],
    popularityRank: null,
    popularityScore: n.popularity_score ?? null,
    trendDirection: 'unknown',
    phoneticKey: soundex(norm),
    tags: n.style_tags ?? [],
    style_tags: n.style_tags ?? [],
    region,
    is_worldwide: region === 'WORLDWIDE',
    source: 'supabase',
    lastUpdated: NOW,
    popularity_score: n.popularity_score ?? null,
  };
}

// Valid Region union values — used to safely narrow NormalizedNameRecord.region (string)
// to the BabyName.region (Region) type at the adapter boundary.
const VALID_REGIONS = new Set<string>([
  'EU', 'US', 'ARABIA', 'MENA', 'ASIA', 'LATIN_AMERICA', 'WORLDWIDE',
]);
function toSafeRegion(r: string): Region {
  return (VALID_REGIONS.has(r) ? r : 'WORLDWIDE') as Region;
}

/**
 * Narrow NormalizedNameRecord back to BabyName for the UI layer.
 * Returns BabyName (not LegacyBabyName) so callers can pass the result
 * directly to AppContext / SwipeCard without a secondary cast.
 * BabyName is assignable to LegacyBabyName, so existing callers are unaffected.
 */
export function toLegacyBabyName(n: NormalizedNameRecord): BabyName {
  return {
    id: n.id,
    name: n.displayName,
    meaning: n.meaning ?? '',
    origin: n.origin ?? '',
    gender: n.gender,
    country: n.country ?? undefined,
    region: toSafeRegion(n.region),
    is_worldwide: n.is_worldwide,
    created_at: n.lastUpdated,
    popularity_rank: n.popularityRank ?? undefined,
    trend: trendDirectionToString(n.trendDirection),
    pronunciation: n.pronunciation ?? undefined,
  };
}

// ─────────────────────────────────────────────────────────────
// Utility helpers
// ─────────────────────────────────────────────────────────────

export function normalizeStr(input: string): string {
  return input
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z]/g, '');
}

export function soundex(name: string): string {
  const s = name.toUpperCase().replace(/[^A-Z]/g, '');
  if (!s) return '0000';
  const MAP: Record<string, string> = {
    B: '1', F: '1', P: '1', V: '1',
    C: '2', G: '2', J: '2', K: '2', Q: '2', S: '2', X: '2', Z: '2',
    D: '3', T: '3',
    L: '4',
    M: '5', N: '5',
    R: '6',
  };
  let code = s[0];
  let prev = MAP[s[0]] ?? '0';
  for (let i = 1; i < s.length && code.length < 4; i++) {
    const curr = MAP[s[i]] ?? '0';
    if (curr !== '0' && curr !== prev) code += curr;
    prev = curr;
  }
  return code.padEnd(4, '0');
}

function genderToUsage(g: string): GenderUsage {
  if (g === 'boy') return 'predominantly_male';
  if (g === 'girl') return 'predominantly_female';
  return 'unisex';
}

function popularityRankToScore(rank?: number | null): number | null {
  if (!rank) return null;
  // rank 1 → score 1000, rank 100+ → score ~0
  return Math.max(0, 1000 - (rank - 1) * 10);
}

function trendStringToDirection(t?: string): TrendDirection {
  if (t === 'rising') return 'rising';
  if (t === 'stable') return 'stable';
  if (t === 'classic') return 'classic';
  return 'unknown';
}

function trendDirectionToString(t: TrendDirection): 'rising' | 'stable' | 'classic' | undefined {
  if (t === 'rising') return 'rising';
  if (t === 'stable') return 'stable';
  if (t === 'classic') return 'classic';
  return undefined;
}

/** Infer a rough language family from a free-text origin string */
function originToLanguageFamily(origin: string | null | undefined): string | null {
  if (!origin) return null;
  const o = origin.toLowerCase();

  if (/french|provençal|occitan/.test(o)) return 'Romance';
  if (/italian|latin|roman/.test(o)) return 'Romance';
  if (/spanish|portuguese/.test(o)) return 'Romance';
  if (/german|germanic|dutch|austrian|flemish/.test(o)) return 'Germanic';
  if (/english|british|anglo/.test(o)) return 'Germanic';
  if (/scandinavian|norse|nordic|swedish|norwegian|danish|finnish/.test(o)) return 'Norse/Nordic';
  if (/greek/.test(o)) return 'Hellenic';
  if (/hebrew|jewish/.test(o)) return 'Semitic';
  if (/arabic|arab/.test(o)) return 'Semitic';
  if (/slavic|russian|polish|czech|serbian|ukrainian/.test(o)) return 'Slavic';
  if (/japanese|jp/.test(o)) return 'Japanese';
  if (/chinese|mandarin|cantonese/.test(o)) return 'Sinitic';
  if (/korean/.test(o)) return 'Korean';
  if (/sanskrit|hindi|indian/.test(o)) return 'Indo-Aryan';
  if (/persian|iranian/.test(o)) return 'Iranian';
  if (/celtic|irish|gaelic|welsh|scottish/.test(o)) return 'Celtic';
  if (/turkish/.test(o)) return 'Turkic';

  return null;
}
