// ============================================================
// NameMatch – Name Enrichment Service
// ============================================================

interface EnrichmentData {
  popularity_rank: number;
  trend: 'rising' | 'stable' | 'classic';
  pronunciation: string;
  similar_names: string[];
}

const ENRICHMENT_MAP: Record<string, EnrichmentData> = {
  Aria:      { popularity_rank: 18, trend: 'rising',  pronunciation: 'AR-ee-ah',    similar_names: ['Ariela', 'Ariana', 'Lyra', 'Mia'] },
  Leo:       { popularity_rank: 4,  trend: 'rising',  pronunciation: 'LEE-oh',       similar_names: ['Leon', 'Levi', 'Lucas', 'Theo'] },
  Mia:       { popularity_rank: 8,  trend: 'stable',  pronunciation: 'MEE-ah',       similar_names: ['Mila', 'Maya', 'Nia', 'Aria'] },
  Luca:      { popularity_rank: 11, trend: 'rising',  pronunciation: 'LOO-kah',      similar_names: ['Lucas', 'Luke', 'Marco', 'Leo'] },
  Emma:      { popularity_rank: 2,  trend: 'classic', pronunciation: 'EM-ah',        similar_names: ['Emily', 'Ella', 'Eva', 'Ema'] },
  Noah:      { popularity_rank: 1,  trend: 'classic', pronunciation: 'NOH-ah',       similar_names: ['Noa', 'Jonas', 'Elijah', 'Liam'] },
  Sofia:     { popularity_rank: 6,  trend: 'stable',  pronunciation: 'so-FEE-ah',    similar_names: ['Sophie', 'Sophia', 'Sofía', 'Lydia'] },
  Oliver:    { popularity_rank: 3,  trend: 'rising',  pronunciation: 'OL-ih-ver',    similar_names: ['Ollie', 'Oscar', 'Owen', 'Elliot'] },
  Luna:      { popularity_rank: 14, trend: 'rising',  pronunciation: 'LOO-nah',      similar_names: ['Lena', 'Stella', 'Aurora', 'Nova'] },
  Elias:     { popularity_rank: 22, trend: 'rising',  pronunciation: 'eh-LY-as',     similar_names: ['Eli', 'Elijah', 'Elliot', 'Isaiah'] },
  Isla:      { popularity_rank: 19, trend: 'rising',  pronunciation: 'EYE-lah',      similar_names: ['Isadora', 'Iris', 'Ivy', 'Ella'] },
  Ethan:     { popularity_rank: 7,  trend: 'stable',  pronunciation: 'EE-than',      similar_names: ['Evan', 'Easton', 'Nathan', 'Liam'] },
  Zara:      { popularity_rank: 31, trend: 'rising',  pronunciation: 'ZAR-ah',       similar_names: ['Zahra', 'Sara', 'Nara', 'Lara'] },
  Julian:    { popularity_rank: 16, trend: 'stable',  pronunciation: 'JOO-lee-an',   similar_names: ['Julius', 'Julien', 'Jasper', 'Damian'] },
  Nora:      { popularity_rank: 24, trend: 'rising',  pronunciation: 'NOR-ah',       similar_names: ['Norah', 'Cora', 'Dora', 'Flora'] },
  'Amélie':  { popularity_rank: 45, trend: 'classic', pronunciation: 'ah-may-LEE',   similar_names: ['Amelie', 'Amelia', 'Emilie', 'Zélie'] },
  Antoine:   { popularity_rank: 38, trend: 'classic', pronunciation: 'an-TWAN',      similar_names: ['Anthony', 'Anton', 'Antonin', 'Mathieu'] },
  Lorenzo:   { popularity_rank: 29, trend: 'stable',  pronunciation: 'lo-REN-zo',    similar_names: ['Leonardo', 'Enzo', 'Marco', 'Matteo'] },
  Chiara:    { popularity_rank: 33, trend: 'stable',  pronunciation: 'kee-AR-ah',    similar_names: ['Clara', 'Giada', 'Lucia', 'Mia'] },
  'Björn':   { popularity_rank: 72, trend: 'classic', pronunciation: 'BYORN',        similar_names: ['Bjarne', 'Erik', 'Lars', 'Sven'] },
  Astrid:    { popularity_rank: 41, trend: 'rising',  pronunciation: 'AH-strid',     similar_names: ['Ingrid', 'Sigrid', 'Freya', 'Solveig'] },
  Alejandro: { popularity_rank: 25, trend: 'stable',  pronunciation: 'ah-leh-HAHN-dro', similar_names: ['Alex', 'Ander', 'Javier', 'Diego'] },
  'Lucía':   { popularity_rank: 12, trend: 'rising',  pronunciation: 'loo-SEE-ah',   similar_names: ['Lucia', 'Luz', 'Luisa', 'Valentina'] },
  Finn:      { popularity_rank: 27, trend: 'rising',  pronunciation: 'FIN',          similar_names: ['Fionn', 'Flynn', 'Cian', 'Ronan'] },
  Aoife:     { popularity_rank: 56, trend: 'classic', pronunciation: 'EE-fah',       similar_names: ['Saoirse', 'Caoimhe', 'Niamh', 'Sinéad'] },
  Liam:      { popularity_rank: 1,  trend: 'classic', pronunciation: 'LEE-am',       similar_names: ['Levi', 'Logan', 'Luke', 'Leo'] },
  Olivia:    { popularity_rank: 1,  trend: 'classic', pronunciation: 'oh-LIV-ee-ah', similar_names: ['Olive', 'Livia', 'Sophia', 'Ava'] },
  Mason:     { popularity_rank: 9,  trend: 'stable',  pronunciation: 'MAY-son',      similar_names: ['Jackson', 'Logan', 'Carter', 'Hudson'] },
  Charlotte: { popularity_rank: 3,  trend: 'classic', pronunciation: 'SHAR-lot',     similar_names: ['Charlie', 'Chloe', 'Clara', 'Claire'] },
  Aiden:     { popularity_rank: 13, trend: 'stable',  pronunciation: 'AY-den',       similar_names: ['Brayden', 'Jayden', 'Hayden', 'Caden'] },
  Harper:    { popularity_rank: 10, trend: 'rising',  pronunciation: 'HAR-per',      similar_names: ['Piper', 'Parker', 'Hadley', 'Sloane'] },
  Maverick:  { popularity_rank: 37, trend: 'rising',  pronunciation: 'MAV-er-ik',    similar_names: ['Maddox', 'Sawyer', 'Phoenix', 'Axel'] },
  Aurora:    { popularity_rank: 20, trend: 'rising',  pronunciation: 'aw-ROR-ah',    similar_names: ['Aurelia', 'Dawn', 'Seraphina', 'Luna'] },
  Asher:     { popularity_rank: 15, trend: 'rising',  pronunciation: 'ASH-er',       similar_names: ['Archer', 'August', 'Atticus', 'Ryder'] },
  Hazel:     { popularity_rank: 23, trend: 'rising',  pronunciation: 'HAY-zel',      similar_names: ['Violet', 'Willow', 'Ivy', 'Olive'] },
  Mohammed:  { popularity_rank: 1,  trend: 'classic', pronunciation: 'moo-HAM-mad',  similar_names: ['Muhammad', 'Ahmad', 'Ahmed', 'Omar'] },
  Fatima:    { popularity_rank: 2,  trend: 'classic', pronunciation: 'FAH-tee-mah',  similar_names: ['Fatimah', 'Khadija', 'Aisha', 'Maryam'] },
  Ahmed:     { popularity_rank: 4,  trend: 'classic', pronunciation: 'AH-med',       similar_names: ['Ahmad', 'Mohammed', 'Omar', 'Hassan'] },
  Aisha:     { popularity_rank: 3,  trend: 'stable',  pronunciation: 'AY-shah',      similar_names: ['Aysha', 'Fatima', 'Noor', 'Layla'] },
  Omar:      { popularity_rank: 5,  trend: 'stable',  pronunciation: 'OH-mar',       similar_names: ['Umar', 'Omer', 'Ahmed', 'Hamza'] },
  Noor:      { popularity_rank: 8,  trend: 'rising',  pronunciation: 'NOOR',         similar_names: ['Nour', 'Nur', 'Layla', 'Yasmin'] },
  Yasmin:    { popularity_rank: 9,  trend: 'stable',  pronunciation: 'YAZ-min',      similar_names: ['Jasmine', 'Yasmeen', 'Noor', 'Layla'] },
  Hassan:    { popularity_rank: 6,  trend: 'classic', pronunciation: 'HAS-san',      similar_names: ['Hussain', 'Hasan', 'Ali', 'Omar'] },
  Layla:     { popularity_rank: 7,  trend: 'rising',  pronunciation: 'LAY-lah',      similar_names: ['Leila', 'Lila', 'Noor', 'Yasmin'] },
  Ibrahim:   { popularity_rank: 10, trend: 'classic', pronunciation: 'ib-rah-HEEM',  similar_names: ['Abraham', 'Brahim', 'Ismail', 'Yusuf'] },
  Kai:       { popularity_rank: 43, trend: 'rising',  pronunciation: 'KY',           similar_names: ['Kei', 'Kenji', 'Ren', 'Ryu'] },
  Sakura:    { popularity_rank: 28, trend: 'rising',  pronunciation: 'sah-KOO-rah',  similar_names: ['Hana', 'Yuki', 'Haru', 'Nozomi'] },
  Kenji:     { popularity_rank: 34, trend: 'classic', pronunciation: 'KEN-jee',      similar_names: ['Kaito', 'Ryota', 'Takumi', 'Yusei'] },
  Arjun:     { popularity_rank: 11, trend: 'rising',  pronunciation: 'AR-joon',      similar_names: ['Aarav', 'Advait', 'Rohan', 'Kiran'] },
  Priya:     { popularity_rank: 14, trend: 'stable',  pronunciation: 'PREE-yah',     similar_names: ['Divya', 'Deepa', 'Ananya', 'Kavya'] },
  Mei:       { popularity_rank: 17, trend: 'stable',  pronunciation: 'MAY',          similar_names: ['Lin', 'Xiu', 'Yue', 'Zhen'] },
  Santiago:  { popularity_rank: 5,  trend: 'rising',  pronunciation: 'san-tee-AH-go', similar_names: ['Santi', 'Mateo', 'Sebastián', 'Felipe'] },
  Valentina: { popularity_rank: 4,  trend: 'rising',  pronunciation: 'val-en-TEE-nah', similar_names: ['Valeria', 'Victoria', 'Isabella', 'Camila'] },
  'Sebastián':{ popularity_rank: 7, trend: 'stable',  pronunciation: 'seh-bas-TYAN', similar_names: ['Sebastian', 'Bastian', 'Alejandro', 'Matteo'] },
  Isabella:  { popularity_rank: 2,  trend: 'classic', pronunciation: 'iz-ah-BEL-ah', similar_names: ['Isabel', 'Isabela', 'Bella', 'Sophia'] },
  Mateo:     { popularity_rank: 3,  trend: 'rising',  pronunciation: 'mah-TEH-oh',   similar_names: ['Matteo', 'Marco', 'Pablo', 'Diego'] },
  Camila:    { popularity_rank: 6,  trend: 'rising',  pronunciation: 'kah-MEE-lah',  similar_names: ['Camilla', 'Camille', 'Valentina', 'Luciana'] },
  Diego:     { popularity_rank: 8,  trend: 'stable',  pronunciation: 'dee-EH-go',    similar_names: ['Rodrigo', 'Emilio', 'Miguel', 'Pablo'] },
  Leonardo:  { popularity_rank: 9,  trend: 'rising',  pronunciation: 'leh-oh-NAR-do', similar_names: ['Leo', 'Lorenzo', 'Luca', 'Marco'] },
  Cyrus:     { popularity_rank: 62, trend: 'rising',  pronunciation: 'SY-rus',        similar_names: ['Darius', 'Caspian', 'Sirius', 'Lyrus'] },
  Shireen:   { popularity_rank: 55, trend: 'classic', pronunciation: 'shee-REEN',    similar_names: ['Shirin', 'Shaheen', 'Leila', 'Nasrin'] },
  Emir:      { popularity_rank: 48, trend: 'rising',  pronunciation: 'eh-MEER',      similar_names: ['Emre', 'Enis', 'Ömer', 'Mert'] },
  Elif:      { popularity_rank: 3,  trend: 'classic', pronunciation: 'eh-LEEF',      similar_names: ['Esra', 'Ayse', 'Zeynep', 'Buse'] },
  Tarek:     { popularity_rank: 32, trend: 'stable',  pronunciation: 'TAH-rek',      similar_names: ['Tariq', 'Walid', 'Karim', 'Jamal'] },
  Nada:      { popularity_rank: 44, trend: 'stable',  pronunciation: 'NAH-dah',      similar_names: ['Nadia', 'Nora', 'Dina', 'Randa'] },
  Amir:      { popularity_rank: 18, trend: 'rising',  pronunciation: 'ah-MEER',      similar_names: ['Emir', 'Samir', 'Tamir', 'Zamir'] },
  Jana:      { popularity_rank: 26, trend: 'rising',  pronunciation: 'JAH-nah',      similar_names: ['Janna', 'Hana', 'Rana', 'Sana'] },
  Thijs:     { popularity_rank: 9,  trend: 'stable',  pronunciation: 'TICE',         similar_names: ['Mathis', 'Timo', 'Tijs', 'Milan'] },
  Fleur:     { popularity_rank: 12, trend: 'classic', pronunciation: 'FLUR',         similar_names: ['Flora', 'Floor', 'Fleurine', 'Claire'] },
  Sanne:     { popularity_rank: 15, trend: 'classic', pronunciation: 'SAH-nuh',      similar_names: ['Sanneke', 'Lotte', 'Evi', 'Femke'] },
  Daan:      { popularity_rank: 4,  trend: 'classic', pronunciation: 'DAHN',         similar_names: ['Dani', 'Sem', 'Bram', 'Noud'] },
  Bram:      { popularity_rank: 6,  trend: 'classic', pronunciation: 'BRAHM',        similar_names: ['Abel', 'Sem', 'Milan', 'Daan'] },
  Jasmijn:   { popularity_rank: 21, trend: 'stable',  pronunciation: 'yas-MINE',     similar_names: ['Yasmin', 'Jasmine', 'Lotte', 'Evi'] },
  Lotte:     { popularity_rank: 8,  trend: 'classic', pronunciation: 'LOT-uh',       similar_names: ['Lotta', 'Lena', 'Evi', 'Sanne'] },
  Milan:     { popularity_rank: 3,  trend: 'rising',  pronunciation: 'MEE-lahn',     similar_names: ['Milo', 'Sem', 'Noud', 'Luca'] },
  Noud:      { popularity_rank: 17, trend: 'rising',  pronunciation: 'NOWD',         similar_names: ['Daan', 'Bram', 'Sem', 'Milan'] },
  Femke:     { popularity_rank: 18, trend: 'classic', pronunciation: 'FEM-kuh',      similar_names: ['Evi', 'Sanne', 'Lotte', 'Fenna'] },
  Sem:       { popularity_rank: 2,  trend: 'classic', pronunciation: 'SEM',          similar_names: ['Sam', 'Bram', 'Daan', 'Milan'] },
  Evi:       { popularity_rank: 11, trend: 'rising',  pronunciation: 'AY-vee',       similar_names: ['Eva', 'Evy', 'Lotte', 'Fleur'] },
  Max:       { popularity_rank: 28, trend: 'stable',  pronunciation: 'MAKS',         similar_names: ['Milo', 'Felix', 'Leo', 'Alex'] },
  Eva:       { popularity_rank: 17, trend: 'classic', pronunciation: 'AY-vah',       similar_names: ['Evi', 'Ava', 'Ella', 'Mia'] },
  Samuel:    { popularity_rank: 27, trend: 'classic', pronunciation: 'SAM-yoo-el',   similar_names: ['Daniel', 'Eli', 'Noah', 'Nathan'] },
  Iris:      { popularity_rank: 26, trend: 'rising',  pronunciation: 'EYE-ris',      similar_names: ['Isla', 'Ivy', 'Clara', 'Nora'] },
  Daniel:    { popularity_rank: 21, trend: 'classic', pronunciation: 'DAN-yel',      similar_names: ['Samuel', 'David', 'Noah', 'Adam'] },
  Camille:   { popularity_rank: 34, trend: 'classic', pronunciation: 'kah-MEEL',     similar_names: ['Camila', 'Lucie', 'Manon', 'Léonie'] },
  Mathis:    { popularity_rank: 22, trend: 'stable',  pronunciation: 'ma-TEES',      similar_names: ['Matteo', 'Mathieu', 'Thijs', 'Theo'] },
  'Léonie':  { popularity_rank: 24, trend: 'rising',  pronunciation: 'lay-oh-NEE',   similar_names: ['Leona', 'Lena', 'Lucie', 'Amélie'] },
  Florian:   { popularity_rank: 31, trend: 'classic', pronunciation: 'FLOR-ee-an',   similar_names: ['Fabian', 'Florent', 'Julian', 'Adrian'] },
  Luisa:     { popularity_rank: 29, trend: 'stable',  pronunciation: 'loo-EE-zah',   similar_names: ['Luiza', 'Lucia', 'Elisa', 'Lina'] },
  Klaus:     { popularity_rank: 52, trend: 'classic', pronunciation: 'KLOWS',        similar_names: ['Niklas', 'Lukas', 'Sven', 'Erik'] },
  Greta:     { popularity_rank: 25, trend: 'rising',  pronunciation: 'GRET-ah',      similar_names: ['Grete', 'Freya', 'Clara', 'Lena'] },
  Sigrid:    { popularity_rank: 36, trend: 'classic', pronunciation: 'SEE-grid',     similar_names: ['Astrid', 'Ingrid', 'Solveig', 'Freya'] },
  Sven:      { popularity_rank: 43, trend: 'classic', pronunciation: 'SVEN',         similar_names: ['Sverre', 'Erik', 'Leif', 'Klaus'] },
  Marco:     { popularity_rank: 30, trend: 'stable',  pronunciation: 'MAR-koh',      similar_names: ['Mateo', 'Lorenzo', 'Luca', 'Leonardo'] },
  Pablo:     { popularity_rank: 18, trend: 'classic', pronunciation: 'PAHB-loh',     similar_names: ['Paolo', 'Mateo', 'Diego', 'Marco'] },
  Elijah:    { popularity_rank: 5,  trend: 'classic', pronunciation: 'eh-LYE-jah',   similar_names: ['Elias', 'Eli', 'Isaiah', 'Noah'] },
  Amelia:    { popularity_rank: 4,  trend: 'classic', pronunciation: 'ah-MEE-lee-ah', similar_names: ['Emilia', 'Emma', 'Mila', 'Amélie'] },
  James:     { popularity_rank: 6,  trend: 'classic', pronunciation: 'JAYMZ',        similar_names: ['Jack', 'Jamie', 'Jacob', 'William'] },
  Evelyn:    { popularity_rank: 8,  trend: 'stable',  pronunciation: 'EV-uh-lin',    similar_names: ['Eva', 'Everly', 'Eleanor', 'Amelia'] },
  Logan:     { popularity_rank: 14, trend: 'stable',  pronunciation: 'LOH-gun',      similar_names: ['Landon', 'Lucas', 'Mason', 'Owen'] },
  Abigail:   { popularity_rank: 16, trend: 'classic', pronunciation: 'AB-ih-gayl',   similar_names: ['Ada', 'Amelia', 'Evelyn', 'Grace'] },
  Wyatt:     { popularity_rank: 19, trend: 'stable',  pronunciation: 'WY-ut',        similar_names: ['Wesley', 'Carter', 'Hudson', 'Owen'] },
  Scarlett:  { popularity_rank: 20, trend: 'rising',  pronunciation: 'SKAR-let',     similar_names: ['Charlotte', 'Violet', 'Ruby', 'Hazel'] },
  Jackson:   { popularity_rank: 22, trend: 'stable',  pronunciation: 'JAK-sun',      similar_names: ['Jaxon', 'Mason', 'Hudson', 'Carter'] },
  Grace:     { popularity_rank: 24, trend: 'classic', pronunciation: 'GRAYSS',       similar_names: ['Faith', 'Rose', 'Claire', 'Abigail'] },
  Carter:    { popularity_rank: 26, trend: 'stable',  pronunciation: 'KAR-ter',      similar_names: ['Carson', 'Cooper', 'Wyatt', 'Mason'] },
  Chloe:     { popularity_rank: 27, trend: 'classic', pronunciation: 'KLOH-ee',      similar_names: ['Zoey', 'Claire', 'Sophie', 'Lily'] },
  Owen:      { popularity_rank: 29, trend: 'stable',  pronunciation: 'OH-en',        similar_names: ['Evan', 'Logan', 'Wyatt', 'Luca'] },
  Penelope:  { popularity_rank: 31, trend: 'rising',  pronunciation: 'puh-NEL-oh-pee', similar_names: ['Phoebe', 'Eloise', 'Hazel', 'Charlotte'] },
  Khalid:    { popularity_rank: 11, trend: 'classic', pronunciation: 'KHAH-lid',     similar_names: ['Walid', 'Karim', 'Faisal', 'Hamza'] },
  Mariam:    { popularity_rank: 12, trend: 'classic', pronunciation: 'MAR-ee-am',    similar_names: ['Maryam', 'Mariamne', 'Fatima', 'Salma'] },
  Yusuf:     { popularity_rank: 13, trend: 'classic', pronunciation: 'YOO-soof',     similar_names: ['Youssef', 'Yasin', 'Ibrahim', 'Omar'] },
  Salma:     { popularity_rank: 15, trend: 'stable',  pronunciation: 'SAL-mah',      similar_names: ['Selma', 'Layla', 'Mariam', 'Noor'] },
  Darius:    { popularity_rank: 47, trend: 'classic', pronunciation: 'DARE-ee-us',   similar_names: ['Cyrus', 'Xerxes', 'Darian', 'Dario'] },
  Parisa:    { popularity_rank: 39, trend: 'stable',  pronunciation: 'pah-REE-sah',  similar_names: ['Pari', 'Nasrin', 'Azadeh', 'Shirin'] },
  Reza:      { popularity_rank: 28, trend: 'classic', pronunciation: 'REH-zah',      similar_names: ['Ramin', 'Amir', 'Karim', 'Mehdi'] },
  Nasrin:    { popularity_rank: 40, trend: 'classic', pronunciation: 'naz-REEN',     similar_names: ['Nastaran', 'Parisa', 'Shireen', 'Azadeh'] },
  Xerxes:    { popularity_rank: 76, trend: 'classic', pronunciation: 'ZERK-seez',    similar_names: ['Cyrus', 'Darius', 'Rostam', 'Arash'] },
  Azadeh:    { popularity_rank: 53, trend: 'classic', pronunciation: 'ah-zah-DEH',   similar_names: ['Parisa', 'Nasrin', 'Shirin', 'Mitra'] },
  Karim:     { popularity_rank: 19, trend: 'stable',  pronunciation: 'kah-REEM',     similar_names: ['Amir', 'Tarek', 'Samir', 'Khalid'] },
  Zineb:     { popularity_rank: 14, trend: 'classic', pronunciation: 'zee-NEB',      similar_names: ['Zeinab', 'Khadija', 'Houda', 'Imane'] },
  Yuki:      { popularity_rank: 16, trend: 'stable',  pronunciation: 'YOO-kee',      similar_names: ['Yuna', 'Aoi', 'Hana', 'Ren'] },
  Haruto:    { popularity_rank: 2,  trend: 'classic', pronunciation: 'hah-ROO-toh',  similar_names: ['Hinata', 'Ren', 'Sora', 'Yuto'] },
  Aoi:       { popularity_rank: 9,  trend: 'rising',  pronunciation: 'AH-oh-ee',     similar_names: ['Yui', 'Mei', 'Ren', 'Hana'] },
  Ren:       { popularity_rank: 7,  trend: 'rising',  pronunciation: 'REN',          similar_names: ['Len', 'Kenji', 'Aoi', 'Yuki'] },
  Hana:      { popularity_rank: 18, trend: 'classic', pronunciation: 'HAH-nah',      similar_names: ['Hanna', 'Sakura', 'Mei', 'Aoi'] },
  Wei:       { popularity_rank: 21, trend: 'stable',  pronunciation: 'WAY',          similar_names: ['Ming', 'Jian', 'Xiu', 'Mei'] },
  'Sofía':   { popularity_rank: 5,  trend: 'classic', pronunciation: 'so-FEE-ah',    similar_names: ['Sofia', 'Sophia', 'Valeria', 'Camila'] },
  Valeria:   { popularity_rank: 10, trend: 'rising',  pronunciation: 'vah-LEH-ree-ah', similar_names: ['Valentina', 'Victoria', 'Camila', 'Luciana'] },
  'Émile':   { popularity_rank: 27, trend: 'classic', pronunciation: 'ay-MEEL',      similar_names: ['Emil', 'Emilio', 'Arthur', 'Mathis'] },
  Manon:     { popularity_rank: 18, trend: 'stable',  pronunciation: 'mah-NON',      similar_names: ['Marion', 'Camille', 'Léonie', 'Amélie'] },
  Arthur:    { popularity_rank: 7,  trend: 'classic', pronunciation: 'AR-thur',      similar_names: ['Archie', 'August', 'Theo', 'Hugo'] },
  Poppy:     { popularity_rank: 21, trend: 'rising',  pronunciation: 'POP-ee',       similar_names: ['Daisy', 'Posy', 'Ruby', 'Lily'] },
  'Álvaro':  { popularity_rank: 23, trend: 'stable',  pronunciation: 'AL-vah-roh',   similar_names: ['Alvaro', 'Alejandro', 'Pablo', 'Mateo'] },
  Marina:    { popularity_rank: 32, trend: 'stable',  pronunciation: 'mah-REE-nah',  similar_names: ['Marisa', 'Mariana', 'Lucia', 'Camila'] },
  Jan:       { popularity_rank: 35, trend: 'classic', pronunciation: 'YAHN',         similar_names: ['Johan', 'Hans', 'Jakub', 'Milan'] },
  Maja:      { popularity_rank: 20, trend: 'stable',  pronunciation: 'MY-ah',        similar_names: ['Maya', 'Mila', 'Mia', 'Aino'] },
  Alva:      { popularity_rank: 19, trend: 'rising',  pronunciation: 'AL-vah',       similar_names: ['Alba', 'Ava', 'Aino', 'Leni'] },
  Nils:      { popularity_rank: 33, trend: 'classic', pronunciation: 'NEELS',        similar_names: ['Niels', 'Leif', 'Sven', 'Erik'] },
  Leif:      { popularity_rank: 41, trend: 'classic', pronunciation: 'LAYF',         similar_names: ['Leiv', 'Nils', 'Sven', 'Erik'] },
  Inga:      { popularity_rank: 38, trend: 'classic', pronunciation: 'ING-ah',       similar_names: ['Ingrid', 'Aino', 'Eleni', 'Sigrid'] },
  Emil:      { popularity_rank: 10, trend: 'classic', pronunciation: 'AY-meel',      similar_names: ['Émile', 'Emilio', 'Milan', 'Arthur'] },
  Freja:     { popularity_rank: 13, trend: 'rising',  pronunciation: 'FRAY-ah',      similar_names: ['Freya', 'Alva', 'Astrid', 'Maja'] },
  Jules:     { popularity_rank: 22, trend: 'stable',  pronunciation: 'ZHOOL',        similar_names: ['Julien', 'Julian', 'Louis', 'Arthur'] },
  Tiago:     { popularity_rank: 11, trend: 'rising',  pronunciation: 'tee-AH-go',    similar_names: ['Thiago', 'Santiago', 'Mateo', 'Enzo'] },
  'Inês':    { popularity_rank: 16, trend: 'classic', pronunciation: 'ee-NESH',      similar_names: ['Ines', 'Aino', 'Ana', 'Maja'] },
  Aino:      { popularity_rank: 14, trend: 'rising',  pronunciation: 'EYE-no',       similar_names: ['Aila', 'Inga', 'Maja', 'Alva'] },
  Eero:      { popularity_rank: 26, trend: 'classic', pronunciation: 'EH-ro',        similar_names: ['Arto', 'Nico', 'Emil', 'Mihai'] },
  Felix:     { popularity_rank: 21, trend: 'stable',  pronunciation: 'FEE-liks',     similar_names: ['Max', 'Leo', 'Nico', 'Oscar'] },
  Leni:      { popularity_rank: 17, trend: 'rising',  pronunciation: 'LAY-nee',      similar_names: ['Lena', 'Mila', 'Alva', 'Inês'] },
  Nico:      { popularity_rank: 24, trend: 'rising',  pronunciation: 'NEE-koh',      similar_names: ['Niko', 'Milo', 'Felix', 'Leo'] },
  Mila:      { popularity_rank: 9,  trend: 'rising',  pronunciation: 'MEE-lah',      similar_names: ['Mia', 'Maja', 'Amelia', 'Leni'] },
  'Seán':    { popularity_rank: 23, trend: 'classic', pronunciation: 'SHAWN',        similar_names: ['Sean', 'Shane', 'Noam', 'Niamh'] },
  Niamh:     { popularity_rank: 12, trend: 'classic', pronunciation: 'NEEV',         similar_names: ['Aoife', 'Saoirse', 'Maeve', 'Eleni'] },
  Jakub:     { popularity_rank: 15, trend: 'classic', pronunciation: 'YAH-koob',     similar_names: ['Jacob', 'Jan', 'Máté', 'Mihai'] },
  Tereza:    { popularity_rank: 18, trend: 'stable',  pronunciation: 'te-REH-zah',   similar_names: ['Teresa', 'Ana', 'Eleni', 'Leni'] },
  'Máté':    { popularity_rank: 13, trend: 'classic', pronunciation: 'MAH-tay',      similar_names: ['Mateo', 'Mathis', 'Mihai', 'Jakub'] },
  Eszter:    { popularity_rank: 20, trend: 'classic', pronunciation: 'ES-ter',       similar_names: ['Esther', 'Eleni', 'Aino', 'Tereza'] },
  Mihai:     { popularity_rank: 19, trend: 'classic', pronunciation: 'mee-HIGH',     similar_names: ['Mikael', 'Jakub', 'Máté', 'Nico'] },
  Ana:       { popularity_rank: 11, trend: 'classic', pronunciation: 'AH-nah',       similar_names: ['Anna', 'Inês', 'Eleni', 'Nora'] },
  Yannis:    { popularity_rank: 28, trend: 'classic', pronunciation: 'YAH-nees',     similar_names: ['Yiannis', 'Nico', 'Elias', 'Theo'] },
  Eleni:     { popularity_rank: 22, trend: 'classic', pronunciation: 'eh-LEH-nee',   similar_names: ['Elena', 'Ana', 'Inga', 'Tereza'] },
  Aleksei:   { popularity_rank: 34, trend: 'classic', pronunciation: 'ah-lek-SAY',   similar_names: ['Alexei', 'Andrei', 'Mihai', 'Nico'] },
  Anastasia: { popularity_rank: 27, trend: 'classic', pronunciation: 'an-ah-STAH-see-ah', similar_names: ['Nastya', 'Natalia', 'Valeria', 'Eleni'] },
  Hamish:    { popularity_rank: 44, trend: 'classic', pronunciation: 'HAY-mish',     similar_names: ['Angus', 'Ewan', 'Arthur', 'Seán'] },
  Lachlan:   { popularity_rank: 23, trend: 'stable',  pronunciation: 'LOCK-lun',     similar_names: ['Logan', 'Hamish', 'Arlo', 'Owen'] },
  Matilda:   { popularity_rank: 14, trend: 'rising',  pronunciation: 'muh-TIL-duh',  similar_names: ['Mathilde', 'Maeve', 'Poppy', 'Leni'] },
  Theo:      { popularity_rank: 12, trend: 'rising',  pronunciation: 'THEE-oh',      similar_names: ['Leo', 'Theo', 'Arthur', 'Milo'] },
  Maeve:     { popularity_rank: 18, trend: 'rising',  pronunciation: 'MAYV',         similar_names: ['Niamh', 'Ava', 'Hazel', 'Poppy'] },
  Arlo:      { popularity_rank: 17, trend: 'rising',  pronunciation: 'AR-loh',       similar_names: ['Milo', 'Theo', 'Leo', 'Lachlan'] },
  Kiri:      { popularity_rank: 29, trend: 'stable',  pronunciation: 'KEER-ee',      similar_names: ['Kira', 'Ayu', 'Lina', 'Mila'] },
  Jiho:      { popularity_rank: 19, trend: 'stable',  pronunciation: 'JEE-ho',       similar_names: ['Ji-ho', 'Minho', 'Jian', 'Ren'] },
  Sujin:     { popularity_rank: 24, trend: 'stable',  pronunciation: 'SOO-jin',      similar_names: ['Soojin', 'Seo-yeon', 'Ha-eun', 'Ayu'] },
  Ayu:       { popularity_rank: 16, trend: 'classic', pronunciation: 'AH-yoo',       similar_names: ['Aoi', 'Ayuu', 'Mei', 'Lina'] },
  Raka:      { popularity_rank: 22, trend: 'stable',  pronunciation: 'RAH-kah',      similar_names: ['Riku', 'Rafi', 'Arjun', 'Kai'] },
  Enzo:      { popularity_rank: 13, trend: 'rising',  pronunciation: 'EN-zoh',       similar_names: ['Lorenzo', 'Leo', 'Milo', 'Tiago'] },
  Anh:       { popularity_rank: 20, trend: 'stable',  pronunciation: 'AHN',          similar_names: ['An', 'Khanh', 'Linh', 'Bao'] },
  Khanh:     { popularity_rank: 21, trend: 'stable',  pronunciation: 'KAHN',         similar_names: ['Anh', 'Minh', 'Linh', 'Bao'] },
  Anan:      { popularity_rank: 25, trend: 'stable',  pronunciation: 'AH-nahn',      similar_names: ['Aiman', 'Niran', 'Raka', 'Kai'] },
  Lalita:    { popularity_rank: 28, trend: 'classic', pronunciation: 'lah-LEE-tah',  similar_names: ['Lalitha', 'Priya', 'Diya', 'Kavya'] },
  Aiman:     { popularity_rank: 17, trend: 'stable',  pronunciation: 'EYE-man',      similar_names: ['Ayman', 'Anan', 'Rafi', 'Hamza'] },
  Nurul:     { popularity_rank: 18, trend: 'classic', pronunciation: 'NOO-rul',      similar_names: ['Noor', 'Noora', 'Lina', 'Ayesha'] },
  Hamza:     { popularity_rank: 12, trend: 'classic', pronunciation: 'HAM-zah',      similar_names: ['Omar', 'Fahad', 'Aiman', 'Yusuf'] },
  Ayesha:    { popularity_rank: 14, trend: 'classic', pronunciation: 'eye-ESH-ah',   similar_names: ['Aisha', 'Noor', 'Lina', 'Ayeshah'] },
  Rafi:      { popularity_rank: 19, trend: 'stable',  pronunciation: 'RAH-fee',      similar_names: ['Rafiq', 'Raka', 'Aiman', 'Hamza'] },
  Nusrat:    { popularity_rank: 26, trend: 'classic', pronunciation: 'NOOS-rat',     similar_names: ['Nasrin', 'Noor', 'Ayesha', 'Meriem'] },
  Youssef:   { popularity_rank: 9,  trend: 'classic', pronunciation: 'yoo-SEF',      similar_names: ['Yusuf', 'Yacine', 'Karim', 'Amine'] },
  Lina:      { popularity_rank: 18, trend: 'rising',  pronunciation: 'LEE-nah',      similar_names: ['Lena', 'Noor', 'Mariam', 'Dana'] },
  Sami:      { popularity_rank: 20, trend: 'classic', pronunciation: 'SAH-mee',      similar_names: ['Samir', 'Amir', 'Rami', 'Karim'] },
  Meriem:    { popularity_rank: 22, trend: 'classic', pronunciation: 'meh-ree-EM',   similar_names: ['Mariam', 'Maryam', 'Lina', 'Noora'] },
  Noam:      { popularity_rank: 8,  trend: 'rising',  pronunciation: 'NOH-am',       similar_names: ['Noah', 'Noor', 'Eli', 'Yael'] },
  Yael:      { popularity_rank: 10, trend: 'classic', pronunciation: 'yah-EL',       similar_names: ['Yara', 'Noam', 'Dana', 'Tala'] },
  Rami:      { popularity_rank: 16, trend: 'stable',  pronunciation: 'RAH-mee',      similar_names: ['Ramy', 'Sami', 'Amir', 'Karim'] },
  Dana:      { popularity_rank: 19, trend: 'stable',  pronunciation: 'DAH-nah',      similar_names: ['Jana', 'Nada', 'Yael', 'Lara'] },
  Zayed:     { popularity_rank: 7,  trend: 'classic', pronunciation: 'ZAH-yed',      similar_names: ['Ziyad', 'Saif', 'Fahad', 'Tamim'] },
  Maha:      { popularity_rank: 13, trend: 'classic', pronunciation: 'MAH-hah',      similar_names: ['Noora', 'Dana', 'Lulwa', 'Reem'] },
  Fahad:     { popularity_rank: 9,  trend: 'classic', pronunciation: 'fah-HAHD',     similar_names: ['Faisal', 'Hamza', 'Tamim', 'Saif'] },
  Reem:      { popularity_rank: 11, trend: 'rising',  pronunciation: 'REEM',         similar_names: ['Reema', 'Rim', 'Noora', 'Maha'] },
  Tamim:     { popularity_rank: 10, trend: 'classic', pronunciation: 'tah-MEEM',     similar_names: ['Tariq', 'Fahad', 'Salman', 'Zayed'] },
  Noora:     { popularity_rank: 12, trend: 'classic', pronunciation: 'NOO-rah',      similar_names: ['Noor', 'Noura', 'Maha', 'Reem'] },
  Salman:    { popularity_rank: 14, trend: 'classic', pronunciation: 'SAL-man',      similar_names: ['Sultan', 'Saif', 'Tamim', 'Fahad'] },
  Lulwa:     { popularity_rank: 23, trend: 'classic', pronunciation: 'LOOL-wah',     similar_names: ['Lulwah', 'Maha', 'Noora', 'Dana'] },
  Said:      { popularity_rank: 21, trend: 'classic', pronunciation: 'sa-EED',       similar_names: ['Saif', 'Sami', 'Salman', 'Tamim'] },
  Mazoon:    { popularity_rank: 25, trend: 'rising',  pronunciation: 'mah-ZOON',     similar_names: ['Mouza', 'Noora', 'Maha', 'Lulwa'] },
  Inti:      { popularity_rank: 27, trend: 'classic', pronunciation: 'EEN-tee',      similar_names: ['Iker', 'Tiago', 'Ayo', 'Rafi'] },
  Nayra:     { popularity_rank: 24, trend: 'rising',  pronunciation: 'NY-rah',       similar_names: ['Naira', 'Nayla', 'Yael', 'Dana'] },
  'Benjamín':{ popularity_rank: 12, trend: 'classic', pronunciation: 'ben-ha-MEEN',  similar_names: ['Benjamin', 'Santiago', 'Mateo', 'Tomás'] },
  Josefa:    { popularity_rank: 18, trend: 'classic', pronunciation: 'ho-SEH-fah',   similar_names: ['Josefina', 'María José', 'Paola', 'Catalina'] },
  Miguel:    { popularity_rank: 14, trend: 'classic', pronunciation: 'mee-GEL',      similar_names: ['Mateo', 'Diego', 'Gabriel', 'Javier'] },
  Ayo:       { popularity_rank: 33, trend: 'rising',  pronunciation: 'AH-yoh',       similar_names: ['Ari', 'Ayoe', 'Amara', 'Thabo'] },
  Amara:     { popularity_rank: 15, trend: 'rising',  pronunciation: 'ah-MAR-ah',    similar_names: ['Amari', 'Amina', 'Aria', 'Naledi'] },
  Kiptoo:    { popularity_rank: 52, trend: 'classic', pronunciation: 'kip-TOO',      similar_names: ['Kip', 'Ayo', 'Thabo', 'Rafi'] },
  Wanjiru:   { popularity_rank: 57, trend: 'classic', pronunciation: 'wan-JEE-roo',  similar_names: ['Naledi', 'Amara', 'Nayra', 'Lina'] },
  Thabo:     { popularity_rank: 29, trend: 'classic', pronunciation: 'TAH-boh',      similar_names: ['Teboho', 'Ayo', 'Kiptoo', 'Said'] },
  Naledi:    { popularity_rank: 21, trend: 'rising',  pronunciation: 'nah-LEH-dee',  similar_names: ['Amara', 'Wanjiru', 'Noora', 'Yael'] },
};

export function enrichName(name: string): Partial<EnrichmentData> {
  return ENRICHMENT_MAP[name] ?? {};
}

export function getTrendLabel(trend?: string): string {
  switch (trend) {
    case 'rising':  return '📈 Trending';
    case 'classic': return '👑 Classic';
    case 'stable':  return '✦ Popular';
    default:        return '';
  }
}

export function getTrendBg(trend?: string): string {
  switch (trend) {
    case 'rising':  return '#FFF8E1';
    case 'classic': return '#EAF2FF';
    case 'stable':  return '#E8F8F1';
    default:        return '#F5F5F5';
  }
}

export function getTrendFg(trend?: string): string {
  switch (trend) {
    case 'rising':  return '#C97D00';
    case 'classic': return '#2F6FE4';
    case 'stable':  return '#1A8A5A';
    default:        return '#888888';
  }
}

export function getNameLength(name: string): 'short' | 'medium' | 'long' {
  if (name.length <= 4) return 'short';
  if (name.length <= 7) return 'medium';
  return 'long';
}
